release: https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html
pop-os/packaging-rust pull request #21
Opened 2024-07-03 20:28 UTC by mmstick

2024-07-03 20:34 UTC, jackpot51 submitted a review, later dismissed

2024-07-03 23:57 UTC, jacobgkau requested changes
I'm getting a library error when trying to test this, both on my physical machine and in a VM (both 22.04).
![screenshot-2024-07-03-23-55-22](https://github.com/pop-os/packaging-rust/assets/7199422/43f2d1e3-d730-4069-a6ab-c9f9491c1f23)
Cargo itself seems to run, but it gives the same library error if I actually try to run a project.

2024-07-05 08:19 UTC, jacobgkau approved these changes
Commit [f5bfa9d](https://github.com/pop-os/packaging-rust/pull/21/commits/f5bfa9d615cf07a6f3bfb4d71a3e0eb48bb82952) is working as expected. rustc & cargo both work.

2024-07-05 15:19 UTC, jackpot51 approved these changes

2024-07-05 15:19 UTC, merged